import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import { DataProvider } from "./context/dataAPI";
import { CartProvider } from "./context/Cartcontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} min-h-screen flex flex-col justify-between ${geistMono.variable} antialiased`}
      >
          <DataProvider>
        <Navbar />
        <div className="flex-grow bg-gradient-to-l from-[#e0c3fc] to-[#8ec5fc]">
            <CartProvider>{children}</CartProvider>
        </div>
          </DataProvider>
        <Footer />
      </body>
    </html>
  );
}
